// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: domain/example_v1.proto

package domain_pb

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationExampleServiceSayHello = "/domain.example.v1.ExampleService/SayHello"

type ExampleServiceHTTPServer interface {
	// SayHello SayHello 返回包含调用参数的问候语。
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

func RegisterExampleServiceHTTPServer(s *http.Server, srv ExampleServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/examples/{name}", _ExampleService_SayHello0_HTTP_Handler(srv))
}

func _ExampleService_SayHello0_HTTP_Handler(srv ExampleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SayHelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExampleServiceSayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*SayHelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SayHelloResponse)
		return ctx.Result(200, reply)
	}
}

type ExampleServiceHTTPClient interface {
	// SayHello SayHello 返回包含调用参数的问候语。
	SayHello(ctx context.Context, req *SayHelloRequest, opts ...http.CallOption) (rsp *SayHelloResponse, err error)
}

type ExampleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewExampleServiceHTTPClient(client *http.Client) ExampleServiceHTTPClient {
	return &ExampleServiceHTTPClientImpl{client}
}

// SayHello SayHello 返回包含调用参数的问候语。
func (c *ExampleServiceHTTPClientImpl) SayHello(ctx context.Context, in *SayHelloRequest, opts ...http.CallOption) (*SayHelloResponse, error) {
	var out SayHelloResponse
	pattern := "/v1/examples/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExampleServiceSayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
