// Code generated by protoc-gen-redact. DO NOT EDIT.
// source: domain/example_v1.proto

package domain_pb

import (
	validate "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	context "context"
	redact "github.com/menta2k/protoc-gen-redact/v3/redact/v3"
	annotations "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ grpc.Server
	_ context.Context
	_ redact.Redactor
	_ codes.Code
	_ status.Status
	_ validate.Rule
	_ annotations.FieldBehavior
)

// RegisterRedactedExampleServiceServer wraps the ExampleServiceServer with the redacted server and registers the service in GRPC
func RegisterRedactedExampleServiceServer(s grpc.ServiceRegistrar, srv ExampleServiceServer, bypass redact.Bypass) {
	RegisterExampleServiceServer(s, RedactedExampleServiceServer(srv, bypass))
}

func RedactedExampleServiceServer(srv ExampleServiceServer, bypass redact.Bypass) ExampleServiceServer {
	if bypass == nil {
		bypass = redact.Falsy
	}
	return &redactedExampleServiceServer{srv: srv, bypass: bypass}
}

type redactedExampleServiceServer struct {
	UnsafeExampleServiceServer
	srv    ExampleServiceServer
	bypass redact.Bypass
}

// SayHello is the redacted wrapper for the actual ExampleServiceServer.SayHello method
// Unary RPC
func (s *redactedExampleServiceServer) SayHello(ctx context.Context, in *SayHelloRequest) (*SayHelloResponse, error) {
	res, err := s.srv.SayHello(ctx, in)
	if !s.bypass.CheckInternal(ctx) {
		// Apply redaction to the response
		redact.Apply(res)
	}
	return res, err
}

// Redact method implementation for SayHelloRequest
func (x *SayHelloRequest) Redact() string {
	if x == nil {
		return ""
	}

	// Safe field: Name
	return x.String()
}

// Redact method implementation for SayHelloResponse
func (x *SayHelloResponse) Redact() string {
	if x == nil {
		return ""
	}

	// Safe field: Message
	return x.String()
}
