// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/lily0749labs/hdyadmin-template/app/admin/internal/security/cert"
	"github.com/lily0749labs/hdyadmin-template/app/admin/internal/server"
	"github.com/lily0749labs/hdyadmin-template/app/admin/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp 描述应用的最小依赖图；新增 Repo、Service 或 Server 后需更新对应 ProviderSet，
// 再执行 make wire 生成实际运行时使用的 wire_gen.go。
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	exampleService := service.NewExampleService(context)
	grpcServer, err := server.NewGRPCServer(context, v, exampleService)
	if err != nil {
		return nil, nil, err
	}
	httpServer, cleanup, err := server.NewHTTPServer(context, exampleService)
	if err != nil {
		return nil, nil, err
	}
	app, err := newApp(context, grpcServer, httpServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
