// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/neo-fork-gotangra/hdyadmin-template/app/admin/internal/security/cert"
	"github.com/neo-fork-gotangra/hdyadmin-template/app/admin/internal/server"
	"github.com/neo-fork-gotangra/hdyadmin-template/app/admin/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp 描述最小依赖图；新增 Repo、Service 或 Server 后更新对应 ProviderSet。
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	exampleService := service.NewExampleService(context)
	grpcServer, err := server.NewGRPCServer(context, v, exampleService)
	if err != nil {
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(context, exampleService)
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
	}, nil
}
