// 模板示例协议。创建实际模块时可以保留它用于连通性检查，也可以替换为业务协议。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: domain/example_v1.proto

package domain_pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SayHelloRequest 是问候接口的请求参数。
type SayHelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 是要写入问候语的名称，长度限制为 1 到 100 个字符。
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_domain_example_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_example_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_domain_example_v1_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SayHelloResponse 是问候接口的响应结果。
type SayHelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message 是服务端生成的完整问候文本。
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_domain_example_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_example_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_domain_example_v1_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_domain_example_v1_proto protoreflect.FileDescriptor

const file_domain_example_v1_proto_rawDesc = "" +
	"\n" +
	"\x17domain/example_v1.proto\x12\x11domain.example.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"3\n" +
	"\x0fSayHelloRequest\x12 \n" +
	"\x04name\x18\x01 \x01(\tB\f\xe0A\x02\xbaH\x06r\x04\x10\x01\x18dR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x82\x01\n" +
	"\x0eExampleService\x12p\n" +
	"\bSayHello\x12\".domain.example.v1.SayHelloRequest\x1a#.domain.example.v1.SayHelloResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/examples/{name}B\xd5\x01\n" +
	"\x15com.domain.example.v1B\x0eExampleV1ProtoP\x01ZFgithub.com/neo-fork-gotangra/hdyadmin-template/api/pb/domain;domain_pb\xa2\x02\x03DEX\xaa\x02\x11Domain.Example.V1\xca\x02\x11Domain\\Example\\V1\xe2\x02\x1dDomain\\Example\\V1\\GPBMetadata\xea\x02\x13Domain::Example::V1b\x06proto3"

var (
	file_domain_example_v1_proto_rawDescOnce sync.Once
	file_domain_example_v1_proto_rawDescData []byte
)

func file_domain_example_v1_proto_rawDescGZIP() []byte {
	file_domain_example_v1_proto_rawDescOnce.Do(func() {
		file_domain_example_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_example_v1_proto_rawDesc), len(file_domain_example_v1_proto_rawDesc)))
	})
	return file_domain_example_v1_proto_rawDescData
}

var file_domain_example_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_example_v1_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: domain.example.v1.SayHelloRequest
	(*SayHelloResponse)(nil), // 1: domain.example.v1.SayHelloResponse
}
var file_domain_example_v1_proto_depIdxs = []int32{
	0, // 0: domain.example.v1.ExampleService.SayHello:input_type -> domain.example.v1.SayHelloRequest
	1, // 1: domain.example.v1.ExampleService.SayHello:output_type -> domain.example.v1.SayHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_example_v1_proto_init() }
func file_domain_example_v1_proto_init() {
	if File_domain_example_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_example_v1_proto_rawDesc), len(file_domain_example_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_example_v1_proto_goTypes,
		DependencyIndexes: file_domain_example_v1_proto_depIdxs,
		MessageInfos:      file_domain_example_v1_proto_msgTypes,
	}.Build()
	File_domain_example_v1_proto = out.File
	file_domain_example_v1_proto_goTypes = nil
	file_domain_example_v1_proto_depIdxs = nil
}
